apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: fortune
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
        - image: devchloe/fortune
          name: html-generator
          volumeMounts:
            - name: html
              mountPath: /var/htdocs
        - image: nginx
          name: web-server
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
          ports:
            - containerPort: 80
              protocol: TCP
      volumes:
        - name: html
          emptyDir: {}
