kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeapp-canary
spec:
  replicas: 1
  template:
    metadata:
      name: kubeapp
      labels:
        app: kubeapp
        env: canary
    spec:
      containers:
      - name: kubeapp
        image: devchloe/app:2.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        command: ["/app"]
        ports:
        - name: kubeapp
          containerPort: 8080