apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ci-cd
  labels:
    name: nginx
spec:
  type: LoadBalancer
  selector:
    name: nginx
    version: "1.10"
  ports:
  - name: http
    port: 80
    targetPort: 80
  
  