kind: Service
apiVersion: v1
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    targetPort: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 몇개의 pod을 한번에 추가할지
      maxUnavailable: 0 # rolling update하는 동안 최대 몇개의 pod이 이용할 수 없어도 되는지
  template:
    metadata:
      labels:
        app: my-app
        version: "2.0"
    spec:
      containers:
      - name: my-app
        image: devchloe/my-app:2.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15 # Intial delay is set to a high value to have a better isibility of the ramped deployment
          periodSeconds: 5


