kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app-v2
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: "2.0"
  template:
    metadata:
      labels: 
        app: my-app
        version: "2.0"
    spec:
      containers:
      - name: my-app
        image: devchloe/my-app:2.0
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /ready
            port: http
        

  