apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary
  namespace: canary
  labels:
    name: nginx
    release: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
      release: canary
  template:
    metadata:
      labels:
        name: nginx
        release: canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
        ports:
        - name: http
          containerPort: 80
