apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: canary
  labels:
    name: nginx
spec:
  type: LoadBalancer
  selector:
    name: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
