apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: hello-node
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: devchloe/hello-node:v2
      
