apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 80 # service가 이용할 포트
    targetPort: 8080 # service가 포워딩할 container 포트
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: kubia

