apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
    role: ${TARGET_ROLE}
    env: prod
spec:
  type: LoadBalancer
  selector:
    matchLables:
      app: tomcat
      role: ${TARGET_ROLE}
  ports:
  - name: http
    port: 80
    targetPort: 8080